title: Covid-19 Data Analysis

theme: minima

plugins:
  - jekyll-relative-links
 
relative_links:
  enabled: true
  collections: true

include:
  - README.md
  - Approach.md
  - DomainInfo.md
  - KnownIssues.md
  - Conclusion.md
  - AboutUs.md

header_pages:
  - Approach.md
  - DomainInfo.md
  - KnownIssues.md
  - Conclusion.md
  - AboutUs.md
