title: Covid-19 Data Analysis

theme: minima

include:
  - README.md
  - Approach.md
  - DomainInfo.md
  - KnownIssues.md
  - Conclusion.md
  - AboutUs.md

header_pages:
  - Approach.md
  - DomainInfo.md
  - KnownIssues.md
  - Conclusion.md
  - AboutUs.md
