title: COVID-19-Death Analysis

theme: minima
layout: default

include:
  - README.md
  - ProjectTeam.md
  - DataSource.md
  - Approach.md
  - DomainKnowledge.md
  - DataUnderstanding.md  
  - DataPreparation.md
  - MachineLearning.md
  - Evaluation.md
  - Conclusion.md

header_pages:
  - ProjectTeam.md
  - DataSource.md
  - Approach.md
  - DomainKnowledge.md
  - DataUnderstanding.md
  - DataPreparation.md
  - MachineLearning.md
  - Evaluation.md
  - Conclusion.md
