theme: minima

plugins:
  - jekyll-relative-links
 
relative_links:
  enabled: true
  collections: true

include:
  - README.md
  - Approach.md
  - RelevantDomainInformation.md

header_pages:
  - README.md
  - Approach.md
  - RelevantDomainInformation.md
