title: Covid-19 Data Analysis

theme: minima
layout: default

include:
  - README.md
  - Dataset.md
  - DomainInfo.md
  - KnownIssues.md
  - Conclusion.md
  - AboutUs.md

header_pages:
  - Dataset.md
  - DomainInfo.md
  - KnownIssues.md
  - Conclusion.md
  - AboutUs.md
